---
layout: post
title: "Testing Error Handling"
date: 2013-05-11 00:01
comments: true
categories: [rails, error-handling, rspec, capybara ]
keywords: Ruby on Rails, Exceptions, Logging, rspec, capybara, phantomjs
description: Clean logging and error handling is a critical aspect of a RoR app.
published: true
canonical: https://www.shakacode.com/blog/testing-error-handling/
---
<p>
How do ensure that your application properly handles errors, especially when
relying on third parties, such as payment processors? Is it easy to verify that
the right things happen when the wrong things happen? Last week's article
<a href="http://www.railsonmaui.com/blog/2013/05/08/strategies-for-rails-logging-and-error-handling/">Strategies for Rails Logging and Error Handling</a> discussed some techniques to
setup a good error handling strategy. Here's some techniques to verify that your
application does what you expect it to do when things go wrong. The key message
is to check how your application handles errors, before your customers do.
</p>

<!-- more -->

<div id="outline-container-sec-1" class="outline-2">
<h2 id="sec-1">Your Code Depends on Outside Systems (That Might Raise Errors)</h2>
<div class="outline-text-2" id="text-1">
<p>
Suppose you've created the super-duper Rails storefront application that takes
online payments. You may even have some unit tests that verify the code. Then
you get the dreaded call that customers are being charged twice and their
orders are not processed. WTF?
</p>

<p>
It's not entirely obvious how to verify proper error handling when outside
systems fail, or even when odd errors are raised from your own code. Payment
processing deserves some special attention because it's a dependency on an
outside service (the payment processor) and will typically require database
updates based on the result of the payment processing. If you're updating
several tables, then you'll want to use a transaction to ensure that all or
nothing saves. While code review and manual testing are good first steps, you
should consider a few extra steps with error handling for sensitive parts of
your application.
</p>
</div>
</div>

<div id="outline-container-sec-2" class="outline-2">
<h2 id="sec-2">Verification of Error Handling Strategy</h2>
<div class="outline-text-2" id="text-2">
<p>
Typically, error handling code is not well tested. It's much more common to test
the "happy path" of everything going right.
</p>

<p>
Let's look at hypothetical example and some tests that can flush out some
errors.
</p>

{% codeblock lang:ruby %}
class Order
  def purchase_cart
    error_message = nil
    Order.transaction do
      # self.user record has charge info, and self.total is the order total
      # PaymentGateway.charge returns either error_message if failed or charge_details if success
      error_message, charge_details = PaymentGateway.charge user, total
      # update the order and the user records with the charge_details
      set_charge_fields_and_save user, charge_details unless error_message # update the order to indicated purchased
      fulfill_order # do lots of complicated stuff to fulfill the order
    end
    error_message # return any error message if there is one
  end
end
{% endcodeblock %}

<p>
So what can go wrong?
</p>
</div>
</div>
<div id="outline-container-sec-3" class="outline-2">
<h2 id="sec-3">Payment Processing is Like a 2-Phase Commit</h2>
<div class="outline-text-2" id="text-3">
<p>
Conceptually, you want a transaction, such that it's all or nothing. If the
charge goes through, then so does everything else. Payment processing like a
2-phase commit, except one has to handle all the what-ifs to be sure that it's
handled correctly.
</p>

<p>
The general steps of payment processing are like this:
</p>
<ol class="org-ol">
<li>Connect to outside resource to make charge.
</li>
<li>Update database records indicating charge successful.
</li>
<li>Fulfill the order.
</li>
</ol>

<p>
Rails transactions work such than any exception in the block will cause the
transaction to be rolled back. The problem with the above code is what happens
if fulfill_order throws an exception? The customer has been charged, the order
was updated to reflect payment, but then <b>ka-boom</b> and an exception is raised,
and any database updates to the order are rolled back, <b>but the payment is not
refunded</b>. The customer is confused as there is a charge but nothing else. How
could you have tested (and avoided) this?
</p>
</div>
</div>
<div id="outline-container-sec-4" class="outline-2">
<h2 id="sec-4">Brute Force Methodology</h2>
<div class="outline-text-2" id="text-4">
<p>
You can simulate error conditions by manually placing =raise "any error message"=
statements in your code, and then testing, say in the UI manually. This is a
good first step to verify that your error handling is working correctly. You
might raise a specific error, if say your payment processor throws a specific
type of error.
</p>

<p>
For the above example, the different methods referenced, such as <code>process_order</code>
can get modified with a single line at the beginning, which would be:
</p>

{% codeblock lang:ruby %}
def process_order
  raise "Any error message"
  # Lots of other code that can be commented out
end
{% endcodeblock %}

<p>
Then go into the UI and test placing an order. Consider the following questions:
</p>
<ol class="org-ol">
<li>Was the right error message displayed to the user?
</li>
<li>Was the right information logged at the correct log level?
</li>
<li>Was an automatic email sent regarding the error?
</li>
</ol>

<p>
See my prior article <a href="http://www.railsonmaui.com/blog/2013/05/08/saner-rails-logging/">Saner Rails Logging</a> for the answers to #2 and #3.
</p>

<p>
By applying this technique to each of the components of completing a purchase,
one can flush out (and handle) nearly all of the different possible errors that
could affect a purchase. Give this technique a try in some critical section of
the code. You'll be surprised how well it works. Before giving you the fix to
the above code, let's see if we can write unit and feature tests on our error
handling.
</p>
</div>
</div>
<div id="outline-container-sec-5" class="outline-2">
<h2 id="sec-5">RSpec Unit Testing of Errors</h2>
<div class="outline-text-2" id="text-5">
<p>
It turns out that with stubbing in <code>rspec</code>, it's easy to test error handling!
<a href="https://www.relishapp.com/rspec/rspec-mocks/v/2-13/docs/method-stubs">RSpec provides a nice mocking library</a>. The test code would look something like
this. Pay attention to the call to <b>stub</b>.
</p>

{% codeblock lang:ruby %}
describe Order do
  describe "#purchase_cart" do
    context "process_order fails" do
      let(:order) { create :order } # factory_girl creation of order and related objects
      before do
        # The magic stubbing of every instance
        Order.any_instance.stub(:fulfill_order) { raise ArgumentError, "test error" }
        # The call to purchase_cart will first call 'charge'
        PaymentGateway.should_receive(:charge).and_return([nil, "charge_details"])
        # The error from within purchase_cart should do a refund
        PaymentGateway.should_receive(:refund).and_return("refund_details")
      end
      it "should throw an error" do
        expect {
          order.purchase_cart
        }.to raise_error
        order.reload
        order.purchased.should_not be
        # charge refunded verified in mock
      end
    end
{% endcodeblock %}

<p>
This test code ensures that the error handling of purchase_cart will catch an
error from fulfill_order, and properly refund the payment and rollback any
changes to the order record.
</p>

<p>
Here's an improved version of the Order#payment_method above:
</p>
{% codeblock lang:ruby %}
class Order
  def purchase_cart
    error_message = nil
    begin
      Order.transaction do
        # user has a credit card info, returns either error_message if failed or charge_details if success
        error_message, charge_details = PaymentGateway.charge user, total
        set_charge_fields_and_save user, charge_details unless error_message # update the order to indicated purchased
      end
      fulfill_order # do lots of complicated stuff to process the order, do this outside of the original tx, so that the payment info can be committed.
    rescue => e
      Utility.log_exception e # Unified strategy for error handling including email notification, see below
      refund_charge if charge_details # If there's an error here, then sys admins will have to manually refund the charge.
      throw e
    end
    error_message # return any error message if there is one
  end
end
{% endcodeblock %}

<p>
Here are the key points to the improved code:
</p>

<ol class="org-ol">
<li>There's a block to catch the exception which is <i>separate from the
transaction block</i>. The <code>rescue</code> properly handles the case of an a charge
being made and needing to be refunded. <code>Utility.log_exception</code> will ensure
that all the right things happen with this sort of error (see <a href="http://www.railsonmaui.com/blog/2013/05/08/saner-rails-logging/">code for
Utlity.logException</a>).
</li>
<li>fulfill_order is moved outside of the transaction block. This allows the
transaction to complete, and then the order_fulfillment takes place. If
there's an issue in fulfilling the order, that can be dealt with separately
from the original charge. In other words, the customer can successfully pay
for the order, and the store can deal with the failure to fulfill the order.
</li>
</ol>
</div>
</div>
<div id="outline-container-sec-6" class="outline-2">
<h2 id="sec-6">RSpec Capybara Feature (Integration) Tests of UI Errors</h2>
<div class="outline-text-2" id="text-6">
<p>
It's possibly more important and sometimes easier to do the verification at the
integration level in RSpec feature specs using <a href="https://github.com/jnicklas/capybara">Capybara</a> with <a href="http://phantomjs.org/">PhantomJs</a> and
<a href="https://github.com/jonleighton/poltergeist">Poltergeist</a>. The secret sauce is the same use of the same stubbing technique as
above to replace some key methods such that they throw an exception. This sort
of technique works amazingly well to ensure that application will do the right
then when an unexpected failure occurs, from the logging and emailing of the
error message to the browser display to then end user.
</p>

<p>
I tend to develop such a test in an iterative manner:
</p>
<ol class="org-ol">
<li>Make sure you've got tests on the "happy" case where the story goes as
planned.
</li>
<li>Then introduce test cases where have bits of code like this that will raise
an error at an opportune time.
{% codeblock lang:ruby %}
Order.any_instance.stub(:fulfill_order) { raise ArgumentError, "test error" }
{% endcodeblock %}
</li>
<li>Allow the test cases to fail, and put in screen shots (in Capybara with
phantomjs, that looks like this:
{% codeblock lang:ruby %}
render_page "a-descriptive-name"
{% endcodeblock %}
<p>
Setup this method <code>render_page</code> in a spec helper file like this:
</p>
{% codeblock lang:ruby %}
def render_page name
  path = File.join Rails.application.config.integration_test_render_dir, "#{name}.png"
  page.driver.render(path)
end
{% endcodeblock %}
</li>
<li>Put in some assertions that the page shows the correct error and the records
in the database have the right values.
</li>
<li>You can even
</li>
</ol>

<p>
Here's an example that tests a failure of the Stripe payment API, including
verification that an email was sent signifying an error:
</p>

{% codeblock lang:ruby %}
 # using gem vcr to record http communication for faster performance
 let(:order) { create :order } # lots of setup in factory girl for non-purchased order

 scenario "Purchase cart, Strip payment error", :vcr do
   # Setup the stub -- the secret sauce to this test
   error_content = "Testing error handling exception message"
   PaymentGateway.stub(:charge) { raise Stripe::InvalidRequestError.new(error_content, 'id') }
   place_order
   page.should have_content error_content
   page.should have_content "Error purchasing"
   order.reload
   order.purchased.should_not be
 end

 def place_order
  login_as(user, :scope => :user)
  visit shopping_cart_path
  page.should have_selector('.total .price', :text => in_dollars(order.total))
  page.render_page("purchase-cart-1")
  click_link "CHECKOUT"
  fill_in_credit_card_info # utility test method to fill in credit card data
  page.should have_selector('.total .price', :text => in_dollars(order.total))
  render_page("purchase-cart-with-payment-info-2")
  click_on "PURCHASE"
  wait_for_spinners # method to wait for the busy spinner to stop
  render_page("purchase-cart-after-click-purchase-3")
  validate_error_emailed
end

# example of how you verify that an error was emailed
def validate_error_emailed
  email = ActionMailer::Base.deliveries.last
  email.should_not be_nil
  email.to.should_not include(order.user.email)
  email.to.should include('whoever@gets-error.com')
end
{% endcodeblock %}
</div>
</div>
<div id="outline-container-sec-7" class="outline-2">
<h2 id="sec-7">Conclusion</h2>
<div class="outline-text-2" id="text-7">
<p>
If you aren't simulating how your application responds to errors, then you'll
eventually find out, and the result might not be as good as you'd prefer. You
can simulate errors with the very simple and quick technique of a well placed
=raise "some error"=, and then testing in a UI. Or you might prefer the
robustness of unit or feature tests using stubbing. Either way, the key message
is to check how your application handles errors, before your customers do.
</p>

<p>
Related Post:
<a href="http://www.railsonmaui.com/blog/2013/05/08/strategies-for-rails-logging-and-error-handling/">Strategies
for Rails Logging and Error Handling</a>
</p>
</div>
</div>
